version: "2"

services:
  sut:
    container_name: machinery_sut
    image: machinery_sut:latest
    depends_on:
      - rabbitmq
      - redis
    links:
      - rabbitmq
      - redis
    build:
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      AMQP_URLS: 'amqp://guest:guest@dummy:5672/,amqp://guest:guest@rabbitmq:5672/'
      AMQP_URLS_SEPARATOR: ','
      REDIS_URL: 'redis:6379'

  rabbitmq:
    container_name: machinery_sut_rabbitmq
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    logging:
      driver: none

  redis:
    container_name: machinery_sut_redis
    image: redis
    logging:
      driver: none
