# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM golang

# Contact maintainer with any issues you encounter
MAINTAINER YUKIMOCHI <naoki_kosaka@yukimochi.jp>

# Set environment variables
ENV PATH /go/bin:$PATH

# Cd into the source code directory
WORKDIR /go/src/github.com/yukimochi/machinery-v1

# Copy the local package files to the container's workspace.
ADD . /go/src/github.com/yukimochi/machinery-v1

# Run integration tests as default command
CMD /go/src/github.com/yukimochi/machinery-v1/wait-for-it.sh rabbitmq:5672 -- make test-with-coverage
