name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          git fetch --prune --unshallow
      - name: Execute Test Script
        run: |
          make ci
